name: Generate Characters Json

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Python 版本的语义版本范围矩阵或准确的版本
        python-version: '3.x'
        # 可选 - x64 或 x86 架构，默认为 x64
        architecture: 'x64'
    - name: Generate Json
      run: python generate.py
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
    - uses: actions/upload-artifact@v2
      with:
        name: characters.json
        path: characters.json
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ steps.date.outputs.date }}
        release_name: release-${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: characters.json
        asset_name: characters.json
        asset_content_type: application/json
    - name: Commit Json
      uses: EndBug/add-and-commit@v5
      with:
        author_name: github-action
        author_email: bot@example.com
        message: Bot: Update characters.json
        branch: release
        add: characters.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}